// Renderer tables: ui/glyphs.py's import-time geometry, ui/font.py's glyph
// overrides and the finder/ strings and times the renderer keys on.
// GENERATED by native/tools/golden_frames.py -- DO NOT EDIT.
// Regenerate: python3 native/tools/golden_frames.py   (check: --check)
#pragma once
#include <stdint.h>

namespace hm {
namespace ui {
namespace U {

// polygons: x, y per vertex (the dart in Q4 px, the rest in px)
constexpr int16_t DART_Q4[8] = {0, -800, 480, 544, 0, 256, -480, 544};
constexpr int16_t DART_KEY_Q4[8] = {0, -895, 540, 617, 0, 293, -540, 617};
constexpr int16_t DART_IN_Q4[8] = {0, -610, 360, 397, 0, 181, -360, 397};
constexpr int16_t CHEV_UP[12] = {-24, 4, 0, -16, 24, 4, 24, 14, 0, -6, -24, 14};
constexpr int16_t CHEV_DN_OUT[16] = {26, -3, 0, 19, -26, -3, -26, -14, -23, -16, 0, 3, 23, -16, 26, -14};
constexpr int16_t CHEV_DN_IN[12] = {22, -5, 0, 13, -22, -5, -22, -10, 0, 9, 22, -10};
constexpr int16_t CHECK_A[12] = {-28, 2, -20, -6, -8, 6, 20, -22, 28, -14, -8, 22};
constexpr int16_t TURN_R[68] = {-12, 22, -18, 18, -22, 12, -24, 6, -25, 0, -24, -6, -22, -13, -18, -18, -12, -22, -6, -24, 0, -25, 6, -24, 12, -22, 18, -18, 22, -13, 24, -6, 25, 0, 19, 0, 18, -5, 16, -10, 13, -13, 9, -16, 5, -18, 0, -19, -5, -18, -9, -16, -13, -13, -16, -10, -18, -5, -19, 0, -18, 5, -16, 9, -13, 13, -9, 16};
constexpr int16_t TURN_R_HEAD[6] = {22, 14, 33, -2, 11, -2};
constexpr int16_t MARK_UP[6] = {0, -6, 6, 5, -6, 5};
constexpr int16_t MARK_DN_OUT[6] = {-6, -5, 6, -5, 0, 6};
constexpr int16_t MARK_DN_IN[6] = {-3, -3, 3, -3, 0, 2};
constexpr int16_t DIAMOND[8] = {0, -3, 3, 0, 0, 3, -3, 0};
// HOT bump view: the 3 rays' butt-ended strokes, then their round caps (x, y per cap)
constexpr int16_t BUMP_RAYS[3][8] = {{-5, -45, -10, -52, -14, -50, -9, -43}, {2, -46, 2, -55, -2, -55, -2, -46}, {9, -43, 14, -50, 10, -52, 5, -45}};
constexpr int16_t BUMP_CAPS[12] = {-7, -44, -12, -51, 0, -46, 0, -55, 7, -44, 12, -51};
// scan bin k's culling rows: y0 (first) and y1 (one past the last)
constexpr uint8_t BIN_Y0[12] = {7, 18, 56, 111, 148, 175, 186, 175, 148, 111, 56, 18};
constexpr uint8_t BIN_Y1[12] = {55, 66, 93, 130, 185, 223, 234, 223, 185, 130, 93, 66};
// rune ops: {kind, x, y, r}; a R_POLY op's x is its index in RUNE_QUADS
constexpr int R_POLY = 0, R_DISC = 1, R_RING = 2, R_CUT = 3;
constexpr uint8_t RUNE_FIRST[9] = {0, 2, 11, 20, 32, 44, 53, 59, 61};
constexpr int16_t RUNE_OPS[61][4] = {{2, 0, 0, 16}, {1, 0, 0, 5}, {0, 0, 0, 0}, {1, 0, -18, 3}, {1, 18, 14, 3}, {0, 1, 0, 0}, {1, 18, 14, 3}, {1, -18, 14, 3}, {0, 2, 0, 0}, {1, -18, 14, 3}, {1, 0, -18, 3}, {0, 3, 0, 0}, {1, -14, 18, 3}, {1, -14, -12, 3}, {0, 4, 0, 0}, {1, 14, 18, 3}, {1, 14, -12, 3}, {0, 5, 0, 0}, {1, -20, -16, 3}, {1, 20, -16, 3}, {0, 6, 0, 0}, {1, -20, 6, 3}, {1, -10, -8, 3}, {0, 7, 0, 0}, {1, -10, -8, 3}, {1, 0, 6, 3}, {0, 8, 0, 0}, {1, 0, 6, 3}, {1, 10, -8, 3}, {0, 9, 0, 0}, {1, 10, -8, 3}, {1, 20, 6, 3}, {0, 10, 0, 0}, {1, 0, -20, 3}, {1, 18, 0, 3}, {0, 11, 0, 0}, {1, 18, 0, 3}, {1, 0, 20, 3}, {0, 12, 0, 0}, {1, 0, 20, 3}, {1, -18, 0, 3}, {0, 13, 0, 0}, {1, -18, 0, 3}, {1, 0, -20, 3}, {0, 14, 0, 0}, {1, 0, 20, 3}, {1, 0, 0, 3}, {0, 15, 0, 0}, {1, 0, 0, 3}, {1, -16, -18, 3}, {0, 16, 0, 0}, {1, 0, 0, 3}, {1, 16, -18, 3}, {0, 17, 0, 0}, {1, 0, -20, 3}, {1, 0, 20, 3}, {0, 18, 0, 0}, {1, -20, 0, 3}, {1, 20, 0, 3}, {1, 0, 0, 18}, {3, 7, -4, 15}};
constexpr int16_t RUNE_QUADS[19][8] = {{-3, -17, 15, 15, 21, 13, 3, -19}, {18, 11, -18, 11, -18, 17, 18, 17}, {-15, 15, 3, -17, -3, -19, -21, 13}, {-11, 18, -11, -12, -17, -12, -17, 18}, {17, 18, 17, -12, 11, -12, 11, 18}, {-20, -13, 20, -13, 20, -19, -20, -19}, {-18, 8, -8, -6, -12, -10, -22, 4}, {-12, -6, -2, 8, 2, 4, -8, -10}, {2, 8, 12, -6, 8, -10, -2, 4}, {8, -6, 18, 8, 22, 4, 12, -10}, {-2, -18, 16, 2, 20, -2, 2, -22}, {16, -2, -2, 18, 2, 22, 20, 2}, {2, 18, -16, -2, -20, 2, -2, 22}, {-16, 2, 2, -18, -2, -22, -20, -2}, {3, 20, 3, 0, -3, 0, -3, 20}, {2, -2, -14, -20, -18, -16, -2, 2}, {2, 2, 18, -16, 14, -20, -2, -2}, {-3, -20, -3, 20, 3, 20, 3, -20}, {-20, 3, 20, 3, 20, -3, -20, -3}};
// ui/font.py OVERRIDE: 8 row bytes (MSB = left pixel) replacing a built-in glyph
constexpr const char FONT_OVERRIDE[] = "1";
constexpr uint8_t FONT_OVERRIDE_ROWS[1][8] = {{0x18, 0x38, 0x78, 0x18, 0x18, 0x18, 0x7E, 0x00}};
constexpr int32_t FACE_SX[4] = {1, 1, 2, 3};
constexpr int32_t FACE_SY[4] = {1, 2, 4, 6};
// keys from finder/
constexpr const char CAL_PAUSE[] = "HOLD STILL";     // pairing.HINT_HOLD_STILL
constexpr const char HINT_FLAT[] = "HOLD FLAT";      // scan.HINT_FLAT
constexpr int32_t SCAN_BLINK_PHASE_MS = 800;   // scan.BLINK_MS
constexpr const char W_FOUND[] = "FOUND";        // game.W_FOUND
constexpr const char W_BUMP[] = "BUMP!";         // game.W_BUMP

}  // namespace U
}  // namespace ui
}  // namespace hm
