"""Tuning constants for the finder logic and renderer.

GENERATED by tools/gen_tuning.py from docs/design/tokens.json -- DO NOT EDIT.
Regenerate with: python3 tools/gen_tuning.py   (check: --check)
Plain constants only; blocks marked 'ui-spec only' come from ui-spec.md.
"""

TOKENS_VERSION = '0.2.0'
TOKENS_HASH = 'f493c57ee22979da'

# ---- Zones (thresholds.zones_m): boundary k is between zone k and k+1
ZONE_FAR = 0
ZONE_NEAR = 1
ZONE_WARM = 2
ZONE_HOT = 3
ZONE_NAMES = ('FAR', 'NEAR', 'WARM', 'HOT')
ZONE_ENTER_M = (28.0, 14.0, 7.0)  # enter closer zone at d <=
ZONE_EXIT_M = (36.0, 18.0, 9.0)  # return to farther zone at d >=
ZONE_DWELL_MS = (3000, 2000, 1500)  # both directions

# ---- Readout bands (thresholds.bands_m)
BAND_EDGES_M = (3.5, 7.0, 14.0, 28.0, 55.0)
BAND_LABELS = ('<3', '~5', '~10', '~20', '~40', '60+')
BAND_HYST = 1.15  # multiplicative, each way
ZONE_BANDS = ((4, 5), (3, 3), (2, 2), (0, 1))  # allowed (lo, hi) band per zone

# ---- Zone tempo (thresholds.zone_tempo), index = zone
ZONE_PERIOD_MS = (2400, 1600, 1000, 500)  # ring spawn = heartbeat base period
ZONE_SPEED_PX_S = (40.0, 56.0, 80.0, 120.0)
ZONE_LEAD_PX = (3, 3, 3, 3)
ZONE_TRAIL_PX = (22, 20, 18, 14)
ZONE_HEARTBEAT = ('TICK', 'TICK', 'DOUBLE', None)
ZONE_HB_EVERY = (2, 1, 1, 1)  # play on every Nth live ring

# ---- Intensity map (field.intensity_map)
FLOOR_A = 0.3
FLOOR_B = 1.3  # floor = A + B*I
GLOW_AMP_A = 2.0
GLOW_AMP_B = 4.0  # glow_amp = A + B*I
PULSE_AMP_A = 4.0
PULSE_AMP_B = 1.5  # pulse_amp = A + B*I
GLOW_R_A = 20.0
GLOW_R_B = 40.0  # glow_r_px = A + B*I
GLOW_R_FOUND = 90.0

# ---- Proximity p(d) and intensity smoothing (thresholds.proximity)
PROX_D_FAR_M = 60.0  # p = clamp01(ln(D_FAR/max(d, D_MIN))/ln(RATIO))
PROX_D_MIN_M = 0.1
PROX_RATIO = 30.0
PROX_LN_RATIO = 3.4011973816621555
INTENSITY_TAU_MS = 1500

# ---- Calibration and path loss (thresholds.calibrate)
CAL_WINDOW_MS = 3000
P1M_NOMINAL_DBM = -45.0
CAL_CLAMP_DB = 6.0  # clamp to nominal +- this
PATH_LOSS_N = 2.6
PATH_LOSS_N_INDOOR = 3.0
CAL_UNSTABLE_SD_DB = 4.0
CAL_SKIP_AFTER_MS = 10000

# ---- Trend gating (thresholds.trend)
TREND_CONF_MIN = 0.6
TREND_WINDOW_MS = 8000
TREND_EVAL_MS = 1000
TREND_HOLD_EVALS = 2
TREND_STRONG_CONF = 0.85
TREND_STRONG_DB = 6.0
TREND_FLIP_MIN_MS = 5000
UNRELIABLE_SD_DB = 7.5
UNRELIABLE_DELIVERY = 0.5

# ---- Direction arrow and sigma model (thresholds.arrow)
ARROW_BORN_MAX_SIGMA_DEG = 45.0
ARROW_STYLES = ('solid_a', 'solid_b', 'outline')
ARROW_TIER_MAX_DEG = (25.0, 45.0, 60.0)  # style = first tier >= cone
ARROW_HIDE_SIGMA_DEG = 60.0  # hidden above this
ARROW_MAX_AGE_MS = 120000
SIGMA_TURN_K = 0.15  # deg per deg turned
SIGMA_STEP_K = 0.7  # deg per step
SIGMA_STILL_K = 1.0  # deg per still second
SIGMA_COLDER_HIT_DEG = 20.0
SIGMA_UNRELIABLE_DEG = 15.0  # display only
SCAN_FLOOR_DEG = 20.0  # s0 = sqrt(sigma_fit^2 + floor^2)
COLDER_HIT_MS = 6000
COLDER_HIT_EVERY_MS = 15000
ARROW_RELINK_RESTORE_MS = 20000

# ---- Scan and walk probe (thresholds.scan, thresholds.probe)
SCAN_DURATION_MS = 12000
SCAN_READY_MS = 3000
SCAN_DEG_PER_S = 30.0
PACER_DEG_PER_S = 30.0  # DIRECTION turn pacer, the scan's rate
SCAN_MIN_P2T_DB = 4.0  # no fix if 2*a1 < this
SCAN_MAX_S0_DEG = 45.0
SCAN_TILT_FAULT_DEG = 35.0
SCAN_TILT_FAULT_MS = 500
SCAN_ABORT_STEPS = 8
SCAN_ABORT_PAUSE_MS = 6000
SCAN_BINS = 12
SCAN_MIN_PACKETS_PER_BIN = 4
PROBE_SIGMA_MIN_DEG = 35.0

# ---- Link, beacons, battery (thresholds.link, beacon_hz, battery_pct)
LINK_LOST_AFTER_MS = 5000
RELINK_PACKETS = 3  # also the SEARCHING exit rule
RELINK_WINDOW_MS = 2000
LIVE_WINDOW_MS = 1000  # ring_live = packet in this window
BEACON_HZ_NORMAL = 10
BEACON_HZ_HOT = 20
BEACON_HZ_SCAN = 20
BEACON_HZ_SAVER = 5
BATT_WARN_PCT = 20
BATT_CRITICAL_PCT = 10
BATT_BANNER_PCT = 5

# ---- FOUND gate (thresholds.found)
BUMP_WINDOW_MS = 400  # both bump spikes within this
FALLBACK_PRESS_WINDOW_MS = 3000
FALLBACK_MAX_BAND = 1  # band <= '~5'

# ---- Bump spike (thresholds.bump_spike, provisional)
BUMP_SPIKE_G = 1.0  # a spike peaks at gravity-removed |a| >= this (§6 HOT)
BUMP_RUN_G = 0.5  # its run: samples above this ...
BUMP_SPIKE_MS = (0, 10)  # ... one sample up to this wide

# ---- Saver and backlight (states.LOW_BATTERY, power.backlight)
SAVER_FPS = 10
SAVER_PULSE_SCALE = 0.7
SAVER_V_MAX = 5.0
SAVER_BACKLIGHT = 0.35
BACKLIGHT_NORMAL = 0.6
BACKLIGHT_BOOST = 1.0
BUTTON_LONG_MS = 1500

# ---- Screen field presets (states): (ramp, I, speed_px_s, period_ms, glow_r_px, pulse_amp)
FIELD_PAIRING_LOOKING = ('green', 0.1, -30.0, 3000, 30.0, 2.0)  # inward rings
FIELD_SEARCHING = ('grey', 0.15, -36.0, 3200, 18.0, 2.5)  # inward rings
FIELD_LINK_LOST = ('grey', None, -30.0, 3000, 16.0, 1.5)  # I frozen at last value
PAIRING_SEEN_BREATHE_AMP = (1.5, 3.0)
PAIRING_SEEN_FLOOR = 0.4
SEARCHING_GLOW_AMP = 1.5
FIELD_LEAD_TRAIL_PX = (3, 22)  # rings outside FAR..HOT
FOUND_LEAD_TRAIL_PX = (3, 24)  # FOUND burst ring
FIELD_SCAN_READY_GLOW_R = 8.0
FIELD_SCAN_READY_PULSE_SCALE = 0.4  # ready: pulse_amp x this
FIELD_SCAN_SWEEP_GLOW_AMP = (1.0, 5.0)  # glow_amp = a + b*I_mirror
FIELD_SCAN_SWEEP_GLOW_R = 12.0  # halo outside the iris
FOUND_PERIOD_MS = 1200  # RenderParams pulse_period_ms in FOUND (no rings travel)

# ---- Haptics (haptics): patterns are on/off ms, starting with on
# priority order, highest first
HAPTIC_NAMES = ('FOUND', 'LOST', 'NOPE', 'HOLD', 'BATT', 'CLOSER', 'FARTHER', 'DOUBLE', 'TICK')
HAPTIC_PATTERNS = {
    'FOUND': (80, 60, 80, 60, 80, 200, 500),
    'LOST': (60, 60, 60, 60, 60, 60, 60, 60, 60),
    'NOPE': (300, 150, 300),
    'HOLD': (400, 200, 400, 200, 400),
    'BATT': (500, 200, 500),
    'CLOSER': (60, 60, 60, 60, 200),
    'FARTHER': (300,),
    'DOUBLE': (60, 80, 60),
    'TICK': (60,),
}
# higher = more important; CLOSER == FARTHER (ui-spec §7)
HAPTIC_RANK = {
    'FOUND': 8,
    'LOST': 7,
    'NOPE': 6,
    'HOLD': 5,
    'BATT': 4,
    'CLOSER': 3,
    'FARTHER': 3,
    'DOUBLE': 1,
    'TICK': 0,
}
HAPTIC_MIN_PULSE_MS = 60
HAPTIC_MIN_GAP_MS = 60
HAPTIC_MAX_DUTY = 0.12
HAPTIC_BLANKING_MS = 150  # accel ignores pulse start .. end + this
HAPTIC_HB_RESUME_MS = 1000  # heartbeats resume this long after an event
HAPTIC_EVENT_GUARD_MS = 1000  # drop an event if >= priority started < this ago

# ---- Colours (color): byte-swapped RGB565 ints for framebuf palettes
C_BG_BASE = 0x0000  # #000000
C_BG_IRIS = 0x6100  # #000C08
C_SURFACE_CHIP = 0xA208  # #081410
C_SURFACE_TOAST = 0x0319  # #182018
C_LINE_SUBTLE = 0x283A  # #394542
C_TEXT_PRIMARY = 0xFFFF  # #FFFFFF
C_TEXT_SECONDARY = 0xB9C6  # #C6D7CE
C_TEXT_TERTIARY = 0x707C  # #7B8E84
C_ACCENT_COLD = 0x586D  # #6BAAC6
C_ACCENT_FOUND = 0xC6FD  # #FFBA31
C_STATUS_WARN = 0xC4FC  # #FF9A21
C_STATUS_CRITICAL = 0x47FA  # #FF4939

# ---- Ramps (ramp)
RAMP_NAMES = ('green', 'gold', 'grey')
# 8 stops
RAMP_SWAPPED = {
    'green': (0xC208, 0x6309, 0x4412, 0x871B, 0xC924, 0x0C36, 0x315F, 0xF9B7),
    'gold': (0x8018, 0x2139, 0x226A, 0x439B, 0xA4D4, 0xC6FD, 0x8EFE, 0x78FF),
    'grey': (0x6108, 0xC310, 0x4521, 0xE731, 0xCA4A, 0xCE6B, 0x3395, 0xBACE),
}
# LUT[j] = ramp position j/63*7, byte-swapped
RAMP_LUT = {
    'green': (
        0xC208, 0xC208, 0xE208, 0x0209, 0x0209, 0x2209, 0x2309, 0x4309, 0x4309, 0x6309,
        0x8309, 0x8309, 0xA309, 0xC309, 0xE409, 0x0412, 0x2412, 0x2412, 0x4412, 0x6412,
        0x8512, 0xA512, 0xC512, 0xE612, 0x261B, 0x461B, 0x671B, 0x871B, 0xA71B, 0xC71B,
        0xE81B, 0x081C, 0x4824, 0x6824, 0x8924, 0xA924, 0xC924, 0xE924, 0x0A25, 0x4A2D,
        0x4A2D, 0x8B2D, 0xAB2D, 0xCB2D, 0xEC35, 0x0C36, 0x2D3E, 0x4D3E, 0x6E46, 0x8E46,
        0xAF4E, 0xCF4E, 0xF056, 0x1057, 0x315F, 0x5267, 0x536F, 0x747F, 0x9587, 0x968F,
        0xB697, 0xD7A7, 0xD8AF, 0xF9B7,
    ),
    'gold': (
        0x8018, 0x8018, 0xA020, 0xC020, 0xC028, 0xE028, 0xE130, 0x0131, 0x0131, 0x2139,
        0x4141, 0x6141, 0x8149, 0xA151, 0xA151, 0xC259, 0xE261, 0x0262, 0x226A, 0x4272,
        0x6272, 0x827A, 0xA282, 0xC282, 0xE38A, 0x0393, 0x2393, 0x439B, 0x63A3, 0x83AB,
        0xC3AB, 0xE3B3, 0x04BC, 0x24C4, 0x64C4, 0x84CC, 0xA4D4, 0xC4DC, 0xE4DC, 0x05E5,
        0x25E5, 0x45ED, 0x65ED, 0x85F5, 0xA6F5, 0xC6FD, 0xE7FD, 0xE8FD, 0x09FE, 0x29FE,
        0x2AFE, 0x4BFE, 0x6CFE, 0x6DFE, 0x8EFE, 0xAFFE, 0xD0FE, 0xD1FE, 0xF2FE, 0x14FF,
        0x35FF, 0x56FF, 0x57FF, 0x78FF,
    ),
    'grey': (
        0x6108, 0x6108, 0x8108, 0x8208, 0x8208, 0xA208, 0xA210, 0xA210, 0xC310, 0xC310,
        0xC310, 0xE310, 0xE418, 0x0419, 0x0419, 0x2419, 0x2421, 0x2521, 0x4521, 0x4521,
        0x6521, 0x8629, 0x8629, 0xA629, 0xA629, 0xC629, 0xC731, 0xE731, 0x0732, 0x083A,
        0x283A, 0x483A, 0x6942, 0x8942, 0xA942, 0xAA4A, 0xCA4A, 0xEA4A, 0x0B53, 0x2B53,
        0x2C5B, 0x4C5B, 0x6D63, 0x8D63, 0xAD6B, 0xCE6B, 0xEF73, 0x0F74, 0x507C, 0x707C,
        0x9184, 0xB184, 0xF28C, 0x128D, 0x3395, 0x549D, 0x95A5, 0xB5A5, 0xD6AD, 0x17B6,
        0x38BE, 0x58BE, 0x99C6, 0xBACE,
    ),
}

# ---- Themes (themes): ramps, lens colour and section 4A numbers per theme
THEME_NAMES = ('ripple', 'sonar', 'tide', 'warp', 'arcade', 'fireflies')  # MENU order; ripple first
THEME_DEFAULT = 'ripple'
# MENU row THEME: <label>
THEME_LABELS = {
    'ripple': 'RIPPLE',
    'sonar': 'SONAR',
    'tide': 'TIDE',
    'warp': 'WARP',
    'arcade': 'ARCADE',
    'fireflies': 'FIREFLIES',
}
# lens colour, byte-swapped (ripple: bg.iris)
THEME_IRIS = {
    'ripple': 0x6100,
    'sonar': 0x6200,
    'tide': 0x4200,
    'warp': 0x2208,
    'arcade': 0x2408,
    'fireflies': 0x2000,
}
# like RAMP_LUT; ripple uses RAMP_LUT
THEME_RAMP_LUT = {
    'sonar': {
        'green': (
            0x8200, 0x8200, 0xA300, 0xC300, 0xC300, 0xE400, 0xE400, 0x0401, 0x0501,
            0x2501, 0x4501, 0x4601, 0x6601, 0x8601, 0x8701, 0xA709, 0xC709, 0xC809,
            0xE809, 0x090A, 0x290A, 0x490A, 0x6A0A, 0x8A0A, 0xAB0A, 0xCB0A, 0xEC0A,
            0x0C0B, 0x2D0B, 0x4D0B, 0x6D0B, 0x8E0B, 0xCE0B, 0xEF13, 0x0F14, 0x3014,
            0x5014, 0x7114, 0xB114, 0xD214, 0xF214, 0x1315, 0x331D, 0x541D, 0x941D,
            0xB51D, 0xD625, 0x162E, 0x3736, 0x5736, 0x983E, 0xB846, 0xD94E, 0x1957,
            0x3A5F, 0x5B6F, 0x5B77, 0x7B87, 0x9C8F, 0x9C9F, 0xBDA7, 0xDDB7, 0xDEBF,
            0xFECF,
        ),
        'gold': (
            0x6010, 0x6010, 0x8018, 0x8018, 0x8020, 0xA020, 0xA028, 0xA028, 0xC028,
            0xC030, 0xE038, 0xE038, 0x0041, 0x2041, 0x4049, 0x6049, 0x6051, 0x8051,
            0xA059, 0xC061, 0xC061, 0xE069, 0x0072, 0x2072, 0x407A, 0x6082, 0x6082,
            0x808A, 0xA092, 0xC09A, 0xE09A, 0xE0A2, 0x00AB, 0x20B3, 0x40B3, 0x60BB,
            0x80C3, 0xA0CB, 0xC0CB, 0xE1D3, 0x01D4, 0x41DC, 0x61DC, 0x81E4, 0xA2E4,
            0xC2EC, 0xE3EC, 0x04F5, 0x45F5, 0x46F5, 0x87F5, 0xA8F5, 0xC9FD, 0xEAFD,
            0x0BFE, 0x2CFE, 0x4EFE, 0x6FFE, 0xB0FE, 0xD2FE, 0xF3FE, 0x14FF, 0x36FF,
            0x57FF,
        ),
        'grey': (
            0x6108, 0x6108, 0x8108, 0x8208, 0x8208, 0xA208, 0xA210, 0xA210, 0xC310,
            0xC310, 0xC310, 0xE310, 0xE418, 0x0419, 0x0419, 0x2419, 0x2421, 0x2521,
            0x4521, 0x4521, 0x6521, 0x8629, 0x8629, 0xA629, 0xA629, 0xC629, 0xC731,
            0xE731, 0x0732, 0x083A, 0x283A, 0x483A, 0x6942, 0x8942, 0xA942, 0xAA4A,
            0xCA4A, 0xEA4A, 0x0B53, 0x2B53, 0x2C5B, 0x4C5B, 0x6D63, 0x8D63, 0xAD6B,
            0xCE6B, 0xEF73, 0x0F74, 0x507C, 0x707C, 0x9184, 0xB184, 0xF28C, 0x128D,
            0x3395, 0x549D, 0x95A5, 0xB5A5, 0xD6AD, 0x17B6, 0x38BE, 0x58BE, 0x99C6,
            0xBACE,
        ),
    },
    'tide': {
        'green': (
            0x4300, 0x4300, 0x6400, 0x6400, 0x6400, 0x8500, 0x8500, 0x8500, 0xA600,
            0xA600, 0xA700, 0xC700, 0xC800, 0xE800, 0xE900, 0x0909, 0x0A09, 0x0A09,
            0x2B09, 0x4C09, 0x4C09, 0x6D09, 0x8D09, 0x8E09, 0xAE09, 0xCF09, 0xCF09,
            0xF009, 0x110A, 0x310A, 0x520A, 0x730A, 0x930A, 0xB412, 0xD512, 0xF512,
            0x1613, 0x3713, 0x571B, 0x781B, 0x981B, 0xD923, 0xF923, 0x1A24, 0x3A2C,
            0x5B2C, 0x9B34, 0xBC3C, 0xDC44, 0x1C4D, 0x3D4D, 0x7D55, 0x9D5D, 0xBE65,
            0xFE6D, 0x1E76, 0x5E86, 0x7E8E, 0xBF9E, 0xDFA6, 0x1FB7, 0x3FBF, 0x7FCF,
            0x9FD7,
        ),
        'gold': (
            0x6018, 0x6018, 0x8020, 0xA020, 0xA028, 0xC028, 0xC130, 0xE130, 0xE130,
            0x0139, 0x2141, 0x2141, 0x4149, 0x6151, 0x8151, 0xA259, 0xA261, 0xC261,
            0xE269, 0x0272, 0x227A, 0x427A, 0x6282, 0x828A, 0xA392, 0xC392, 0xE39A,
            0x03A3, 0x23AB, 0x43B3, 0x83B3, 0xA3BB, 0xC4C3, 0xE4CB, 0x24CC, 0x44D4,
            0x64DC, 0x84DC, 0xA5E4, 0xC5E4, 0xE5EC, 0x06ED, 0x26F5, 0x46F5, 0x67FD,
            0x87FD, 0xA8FD, 0xC9FD, 0xEAFD, 0x0AFE, 0x0BFE, 0x2CFE, 0x4DFE, 0x6EFE,
            0x8FFE, 0xB0FE, 0xD1FE, 0xD2FE, 0xF3FE, 0x15FF, 0x36FF, 0x57FF, 0x58FF,
            0x79FF,
        ),
        'grey': (
            0x6108, 0x6108, 0x8108, 0x8208, 0x8208, 0xA208, 0xA210, 0xA210, 0xC310,
            0xC310, 0xC310, 0xE310, 0xE418, 0x0419, 0x0419, 0x2419, 0x2421, 0x2521,
            0x4521, 0x4521, 0x6521, 0x8629, 0x8629, 0xA629, 0xA629, 0xC629, 0xC731,
            0xE731, 0x0732, 0x083A, 0x283A, 0x483A, 0x6942, 0x8942, 0xA942, 0xAA4A,
            0xCA4A, 0xEA4A, 0x0B53, 0x2B53, 0x2C5B, 0x4C5B, 0x6D63, 0x8D63, 0xAD6B,
            0xCE6B, 0xEF73, 0x0F74, 0x507C, 0x707C, 0x9184, 0xB184, 0xF28C, 0x128D,
            0x3395, 0x549D, 0x95A5, 0xB5A5, 0xD6AD, 0x17B6, 0x38BE, 0x58BE, 0x99C6,
            0xBACE,
        ),
    },
    'warp': {
        'green': (
            0x2308, 0x2308, 0x2408, 0x2408, 0x2408, 0x2508, 0x4510, 0x4510, 0x4610,
            0x4610, 0x4710, 0x4710, 0x6818, 0x6818, 0x6918, 0x6918, 0x6A20, 0x8A20,
            0x8B20, 0x8C20, 0xAC20, 0xAD28, 0xAD28, 0xCE28, 0xCE28, 0xCF28, 0xEF30,
            0xF030, 0xF130, 0x1139, 0x3239, 0x3341, 0x5341, 0x5449, 0x7549, 0x7549,
            0x9651, 0xB759, 0xD759, 0xF861, 0x1862, 0x396A, 0x596A, 0x7A72, 0x9A72,
            0xBB7A, 0xDB82, 0x1C83, 0x5C8B, 0x7C93, 0xBD93, 0xDD9B, 0x1DA4, 0x5EA4,
            0x7EAC, 0xDEB4, 0x1EBD, 0x5EC5, 0xBFCD, 0xFFD5, 0x5FD6, 0x9FDE, 0xFFE6,
            0x3FEF,
        ),
        'gold': (
            0x8018, 0x8018, 0xA020, 0xC020, 0xC028, 0xE028, 0xE130, 0x0131, 0x0131,
            0x2139, 0x4141, 0x6141, 0x8149, 0xA151, 0xA151, 0xC259, 0xE261, 0x0262,
            0x226A, 0x4272, 0x6272, 0x827A, 0xA282, 0xC282, 0xE38A, 0x0393, 0x2393,
            0x439B, 0x63A3, 0x83AB, 0xC3AB, 0xE3B3, 0x04BC, 0x24C4, 0x64C4, 0x84CC,
            0xA4D4, 0xC4DC, 0xE4DC, 0x05E5, 0x25E5, 0x45ED, 0x65ED, 0x85F5, 0xA6F5,
            0xC6FD, 0xE7FD, 0xE8FD, 0x09FE, 0x29FE, 0x2AFE, 0x4BFE, 0x6CFE, 0x6DFE,
            0x8EFE, 0xAFFE, 0xD0FE, 0xD1FE, 0xF2FE, 0x14FF, 0x35FF, 0x56FF, 0x57FF,
            0x78FF,
        ),
        'grey': (
            0x6108, 0x6108, 0x8108, 0x8208, 0x8208, 0xA208, 0xA210, 0xA210, 0xC310,
            0xC310, 0xC310, 0xE310, 0xE418, 0x0419, 0x0419, 0x2419, 0x2421, 0x2521,
            0x4521, 0x4521, 0x6521, 0x8629, 0x8629, 0xA629, 0xA629, 0xC629, 0xC731,
            0xE731, 0x0732, 0x083A, 0x283A, 0x483A, 0x6942, 0x8942, 0xA942, 0xAA4A,
            0xCA4A, 0xEA4A, 0x0B53, 0x2B53, 0x2C5B, 0x4C5B, 0x6D63, 0x8D63, 0xAD6B,
            0xCE6B, 0xEF73, 0x0F74, 0x507C, 0x707C, 0x9184, 0xB184, 0xF28C, 0x128D,
            0x3395, 0x549D, 0x95A5, 0xB5A5, 0xD6AD, 0x17B6, 0x38BE, 0x58BE, 0x99C6,
            0xBACE,
        ),
    },
    'arcade': {
        'green': (
            0x6610, 0x6610, 0x6610, 0x6610, 0x6610, 0x8920, 0x8920, 0x8920, 0x8920,
            0x8920, 0x8920, 0x8920, 0x8920, 0x8920, 0xAC30, 0xAC30, 0xAC30, 0xAC30,
            0xAC30, 0xAC30, 0xAC30, 0xAC30, 0xAC30, 0x1159, 0x1159, 0x1159, 0x1159,
            0x1159, 0x1159, 0x1159, 0x1159, 0x1159, 0x5499, 0x5499, 0x5499, 0x5499,
            0x5499, 0x5499, 0x5499, 0x5499, 0x5499, 0xD3E9, 0xD3E9, 0xD3E9, 0xD3E9,
            0xD3E9, 0xD3E9, 0xD3E9, 0xD3E9, 0xD3E9, 0x78FC, 0x78FC, 0x78FC, 0x78FC,
            0x78FC, 0x78FC, 0x78FC, 0x78FC, 0x78FC, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
            0xFFFF,
        ),
        'gold': (
            0x8118, 0x8118, 0x8118, 0x8118, 0x8118, 0x2139, 0x2139, 0x2139, 0x2139,
            0x2139, 0x2139, 0x2139, 0x2139, 0x2139, 0x216A, 0x216A, 0x216A, 0x216A,
            0x216A, 0x216A, 0x216A, 0x216A, 0x216A, 0x42B3, 0x42B3, 0x42B3, 0x42B3,
            0x42B3, 0x42B3, 0x42B3, 0x42B3, 0x42B3, 0xC2EC, 0xC2EC, 0xC2EC, 0xC2EC,
            0xC2EC, 0xC2EC, 0xC2EC, 0xC2EC, 0xC2EC, 0x47FE, 0x47FE, 0x47FE, 0x47FE,
            0x47FE, 0x47FE, 0x47FE, 0x47FE, 0x47FE, 0x51FF, 0x51FF, 0x51FF, 0x51FF,
            0x51FF, 0x51FF, 0x51FF, 0x51FF, 0x51FF, 0xFFFF, 0xFFFF, 0xFFFF, 0xFFFF,
            0xFFFF,
        ),
        'grey': (
            0x8310, 0x8310, 0x8310, 0x8310, 0x8310, 0xC518, 0xC518, 0xC518, 0xC518,
            0xC518, 0xC518, 0xC518, 0xC518, 0xC518, 0x4729, 0x4729, 0x4729, 0x4729,
            0x4729, 0x4729, 0x4729, 0x4729, 0x4729, 0xE939, 0xE939, 0xE939, 0xE939,
            0xE939, 0xE939, 0xE939, 0xE939, 0xE939, 0xAD52, 0xAD52, 0xAD52, 0xAD52,
            0xAD52, 0xAD52, 0xAD52, 0xAD52, 0xAD52, 0xF17B, 0xF17B, 0xF17B, 0xF17B,
            0xF17B, 0xF17B, 0xF17B, 0xF17B, 0xF17B, 0x56A5, 0x56A5, 0x56A5, 0x56A5,
            0x56A5, 0x56A5, 0x56A5, 0x56A5, 0x56A5, 0xDBD6, 0xDBD6, 0xDBD6, 0xDBD6,
            0xDBD6,
        ),
    },
    'fireflies': {
        'green': (
            0x4100, 0x4100, 0x6100, 0x6100, 0x6100, 0x8100, 0x8108, 0x8108, 0xA108,
            0xA108, 0xA108, 0xC108, 0xC108, 0xC108, 0xE108, 0xE210, 0xE210, 0x0211,
            0x0211, 0x2211, 0x2211, 0x4219, 0x6219, 0x6219, 0x8319, 0xA321, 0xA321,
            0xC321, 0xE321, 0x032A, 0x432A, 0x632A, 0x8432, 0xA432, 0xC432, 0x043B,
            0x243B, 0x6443, 0x844B, 0xC453, 0x0454, 0x445C, 0x8564, 0xC56C, 0xE574,
            0x257D, 0x6585, 0x868D, 0xC695, 0x079E, 0x27A6, 0x68AE, 0xA8B6, 0xC9BE,
            0x09C7, 0x2BCF, 0x4CCF, 0x4ED7, 0x70DF, 0x91DF, 0xB3E7, 0xD5EF, 0xD6EF,
            0xF8F7,
        ),
        'gold': (
            0x8018, 0x8018, 0xA020, 0xC020, 0xC028, 0xE028, 0xE130, 0x0131, 0x0131,
            0x2139, 0x4141, 0x6141, 0x8149, 0xA151, 0xA151, 0xC259, 0xE261, 0x0262,
            0x226A, 0x4272, 0x6272, 0x827A, 0xA282, 0xC282, 0xE38A, 0x0393, 0x2393,
            0x439B, 0x63A3, 0x83AB, 0xC3AB, 0xE3B3, 0x04BC, 0x24C4, 0x64C4, 0x84CC,
            0xA4D4, 0xC4DC, 0xE4DC, 0x05E5, 0x25E5, 0x45ED, 0x65ED, 0x85F5, 0xA6F5,
            0xC6FD, 0xE7FD, 0xE8FD, 0x09FE, 0x29FE, 0x2AFE, 0x4BFE, 0x6CFE, 0x6DFE,
            0x8EFE, 0xAFFE, 0xD0FE, 0xD1FE, 0xF2FE, 0x14FF, 0x35FF, 0x56FF, 0x57FF,
            0x78FF,
        ),
        'grey': (
            0x6108, 0x6108, 0x8108, 0x8208, 0x8208, 0xA208, 0xA210, 0xA210, 0xC310,
            0xC310, 0xC310, 0xE310, 0xE418, 0x0419, 0x0419, 0x2419, 0x2421, 0x2521,
            0x4521, 0x4521, 0x6521, 0x8629, 0x8629, 0xA629, 0xA629, 0xC629, 0xC731,
            0xE731, 0x0732, 0x083A, 0x283A, 0x483A, 0x6942, 0x8942, 0xA942, 0xAA4A,
            0xCA4A, 0xEA4A, 0x0B53, 0x2B53, 0x2C5B, 0x4C5B, 0x6D63, 0x8D63, 0xAD6B,
            0xCE6B, 0xEF73, 0x0F74, 0x507C, 0x707C, 0x9184, 0xB184, 0xF28C, 0x128D,
            0x3395, 0x549D, 0x95A5, 0xB5A5, 0xD6AD, 0x17B6, 0x38BE, 0x58BE, 0x99C6,
            0xBACE,
        ),
    },
}
# ui-spec section 4A numbers
THEME_PARAMS = {
    'sonar': {
        'beams': (2, 3, 4, 6),
        'trail_deg': (30, 70),
        'trail_amp': (3, 4),
        'range_rings_px': (40, 80, 120),
        'range_level': (1.0, 0.8),
        'listen_deg_s': 60,
        'breathe_ms': 2400,
        'ping_px_s': 240,
    },
    'tide': {
        'levels': {'<3': 0.86, '~5': 0.74, '~10': 0.62, '~20': 0.5, '~40': 0.38, '60+': 0.26},
        'level_found': 0.92,
        'level_listen': 0.2,
        'ease_ms': 450,
        'wave_amp_px': ((1.5, 1.1), (0.6, 0.5)),
        'wave_px_s': (14, 12),
        'swell_px': (5, 3),
        'swell_ms': 240,
        'bubbles': (2, 2),
        'bubble_px_s': (22, 12),
        'drip_ms': 3000,
        'shimmer_band_px': 24,
    },
    'warp': {
        'stars': (18, 30, 46, 70),
        'rate': (0.45, 0.65, 0.95, 1.45),
        'surge': 1.3,
        'surge_ms': 170,
        'listen_stars': 14,
        'listen_rate': -0.22,
        'still_stars': 30,
        'scan_stars': 24,
        'found_stars': 56,
        'found_rate': 1.6,
        'found_ms': 400,
    },
    'arcade': {
        'cell_px': 8,
        'tick_ms': 100,
        'front_levels': (7.0, 4.6, 2.6),
        'front_scale': (0.62, 0.38),
        'core_cells': (1, 3),
        'listen_ticks_per_cell': 2,
    },
    'fireflies': {
        'count': (5, 9, 14, 22),
        'sync': (0.25, 0.5, 0.8, 1.0),
        'rise_ms': 90,
        'fall_ms': 260,
        'halo': 0.9,
        'orbit_shrink': 0.45,
        'listen_specks': 3,
        'listen_ms': 7000,
        'still_count': 9,
        'found_count': 22,
        'breathe_ms': 2400,
    },
}

# ---- Layout (layout): rects are (x, y, w, h)
CENTER = (120, 120)
TOP_SLOT = (12, 12, 216, 24)
BOTTOM_SLOT = (24, 186, 192, 40)
IRIS_R = {'none': 0, 'chevrons': 44, 'arrow': 64, 'scan': 64, 'runes': 92, 'seeker': 44}
BEAM_R = 60
SWEEP_R_INNER = 70
SWEEP_R_OUTER = 110
RUNE_CENTERS_X = (64, 120, 176)
CORE_DOT_R = 6
CORE_DOT_LEVEL = 6.0

# ---- Typography (typography)
WORD_MAX_CHARS = 10
LABEL_MAX_CHARS = 18
WORD_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 !'=:+%~<"
LABEL_CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 ~<>+%:-?,/'

# ---- Motion (motion)
FPS_TARGET = 20
FPS_LOCKS = (20, 10, 8, 7, 6, 5)  # frame lock rates, fastest first (app/pacer.py)
BREATHE_PAIRING_MS = 2400  # PAIRING seen halo breathing
TOAST_MS = 2500
ZONE_CROSSFADE_MS = 600
HUE_CROSSFADE_MS = 1500
HUE_CROSSFADE_FOUND_MS = 400
IRIS_ANIM_MS = 300
SCAN_MORPH_MS = 400
ARROW_APPEAR_MS = 250
ARROW_APPEAR_SCALE = 0.6
ARROW_ANGLE_TAU_MS = 200
ARROW_ANGLE_DEADBAND_DEG = 4.0
CHEVRON_NUDGE_MS = 800
CHEVRON_NUDGE_PX = 6
TOAST_IN_MS = 200
TOAST_IN_PX = 12
TOAST_OUT_MS = 150
FLASH_LIMIT_STEPS = 2
FLASH_LIMIT_MS = 333
TEMPORAL_AA_K = 1.5  # lead_eff = max(lead, K*|speed|/fps)

# ---- Ripple field (field)
FIELD_R_MAX = 168  # ring-map max index; inward rings spawn here
VIGNETTE_STOPS = ((0, 1.0), (88, 1.0), (120, 0.4), (168, 0.15))  # (index, gain), linear between
FADEIN_PX = 12
GHOST_AMP_SCALE = 0.6
IRIS_RIM_PX = 3
IRIS_RIM_MIN_LEVEL = 5.0  # rim level min(7, max(this, floor+glow_amp))
BURST_AMP = 7.0
FOUND_BURST_SPEED_PX_S = 240.0
STANDING_BASE = 2.0
STANDING_AMP = 2.5
STANDING_WAVELENGTH_PX = 32
STANDING_BREATHE = (0.6, 0.4)  # (0.6 + 0.4 sin)
STANDING_PERIOD_MS = 2400

# ---- Glyph geometry (glyphs), relative to CENTER, pointing up
DART_PTS = ((0, -50), (30, 34), (0, 16), (-30, 34))
CHEVRON_UP_PTS = ((-24, 4), (0, -16), (24, 4), (24, 14), (0, -6), (-24, 14))
CHEVRON_STACK_PX = 16
CHECK_PTS = ((-28, 2), (-20, -6), (-8, 6), (20, -22), (28, -14), (-8, 22))
CHECK_DISC_R = 40
SEEKER_RING = (14, 4)  # (r, stroke)
SEEKER_TICKS = ((0, 90, 180, 270), 20, 28, 4)  # (angles, r_from, r_to, stroke)
TURN_ARC = (22, -150, 90, 6)  # (r, from_deg, to_deg, stroke)
TURN_HEAD_PTS = ((22, 14), (33, -2), (11, -2))
RUNE_STROKE = 6
# (name, prims)
RUNES = (
    ('sun', (('ring', 0, 0, 16), ('disc', 0, 0, 5))),
    ('peak', (('closed', ((0, -18), (18, 14), (-18, 14))),)),
    (
        'gate',
        (
            ('line', (-14, 18), (-14, -12)),
            ('line', (14, 18), (14, -12)),
            ('line', (-20, -16), (20, -16)),
        ),
    ),
    ('wave', (('open', ((-20, 6), (-10, -8), (0, 6), (10, -8), (20, 6))),)),
    ('diamond', (('closed', ((0, -20), (18, 0), (0, 20), (-18, 0))),)),
    (
        'fork',
        (
            ('line', (0, 20), (0, 0)),
            ('line', (0, 0), (-16, -18)),
            ('line', (0, 0), (16, -18)),
        ),
    ),
    ('cross', (('line', (0, -20), (0, 20)), ('line', (-20, 0), (20, 0)))),
    ('moon', (('disc', 0, 0, 18), ('cut_disc', 7, -4, 15))),
)
LINK_BARS = (4, 2, (4, 7, 10, 13))  # (w, gap, heights)
LINK_Q_MAX = 4  # status link bars 0..count

# ---- ui-spec only: Screens and phases (ui-spec §3)
LOGIC_MS = 100  # logic rate: one RenderParams per 100 ms (10 Hz)
SCREENS = (
    'PAIRING', 'SEARCHING', 'FAR', 'NEAR', 'WARM', 'HOT', 'FOUND', 'SCANNING',
    'LINK_LOST', 'MENU',
)
SUBS_PAIRING = ('looking', 'seen', 'confirmed', 'calibrate', 'split')
SUBS_SCANNING = ('ready', 'sweep', 'result')
SUBS_DIRECTION = ('reveal', 'turn', 'walk')  # FAR..HOT sub (or None)
SUBS_FOUND = ('celebrate', 'result')
GLYPHS = (
    'glow', 'seeker', 'chevrons', 'arrow', 'countdown', 'turn', 'check', 'runes',
    'battery',
)
BANNER_SEVERITIES = ('info', 'warn', 'critical')
HEARTBEATS = ('TICK', 'DOUBLE')
SPEED_MIN_PX_S = -60.0
SPEED_MAX_PX_S = 240.0
PERIOD_MIN_MS = 400
PERIOD_MAX_MS = 4000
WAVELENGTH_MAX_PX = 140.0
WAVELENGTH_TOL_PX = 1.0  # wavelength == |speed| * period / 1000 within this
GLOW_R_MAX_PX = 96.0
CONE_DRAW_MIN_DEG = 12.0  # cone half-angle is clamped to 12..60 for drawing
FPS_CAP_MIN = 5  # the slowest frame lock (motion.fps.locks)
FPS_CAP_MAX = 20  # the fastest frame lock (motion.fps.locks)
COUNTDOWN_MAX = 99  # 2-digit type.display countdown (split 30..0)

# ---- ui-spec only: Per-screen field extras (ui-spec §6)
MENU_PALETTE_SCALE = 0.5
BURST_SPEED_MULT = 2.0  # burst ring speed = 2x zone speed (§4)

# ---- ui-spec only: Mirror, trend, direction extras (ui-spec §5)
MIRROR_EMA_MS = 150  # live mirror RSSI EMA (§5.7)
MIRROR_MIN_SPAN_DB = 4.0  # I_mirror denominator floor
TREND_START_DB = 3.0  # +1 at >= 3 dB / 8 s starting threshold (§5.5)
UNRELIABLE_WINDOW_MS = 5000  # delivery window for 'unreliable' (§5.5)
NOISE_EMA_ALPHA = 0.02  # noise_db: EMA of |own RSSI step| (§5.5)
NOISE_PAIR_GAP_MS = 1000  # own packets further apart don't form a pair (§5.5)
DIRECTION_REVEAL_MS = 1500
DIRECTION_CLOCK_MAX_SIGMA_DEG = 30.0  # clock-hour word if sigma <= 30
DIRECTION_AHEAD_DEG = 20.0  # |theta| <= 20 -> AHEAD, turn skipped
DIRECTION_LOCK_EASE_MS = 300
DIRECTION_WALK_WORD_MS = 3000
ARROW_EXPIRE_MS = 600
PACER_TICK_DEG = 45.0

# ---- ui-spec only: Scan extras (ui-spec §6 SCANNING)
SCAN_FLAT_DEG = 20.0  # face-up within 20 deg ...
SCAN_FLAT_HOLD_MS = 500  # ... held 0.5 s
SCAN_WALK_STEPS = 3  # >= 3 steps in 2 s pauses the sweep
SCAN_WALK_WINDOW_MS = 2000
SCAN_TICK_DEG = 45.0  # TICK every 45 deg, DOUBLE at 180
SCAN_BLINK_MS = 200
SCAN_PEER_WALK_WIDEN_MS = 2000  # peer walking > 2 s of sweep: +15 deg to s0
SCAN_PEER_WALK_WIDEN_DEG = 15.0
SCAN_PEER_WALK_FAIL_MS = 4000  # > 4 s: no fix, FRIEND MOVED
SCAN_HOLD_REPEAT_MS = 3000  # partner HOLD haptic repeat
SCAN_HOLD_REPEAT_MAX = 3

# ---- ui-spec only: Frame lock (ui-spec §4 rule 6; app/pacer.py)
FPS_COST_N = 16  # frame cost = 2nd largest busy ms of the last 16 frames
FPS_MARGIN_PCT = 10  # a faster lock needs cost + 10 % to fit its period
FPS_RAISE_MS = 3000  # ... for this long before the lock rises one step
FPS_LOG_MS = 10000  # serial fps line period (main.py)

# ---- ui-spec only: Pairing, found, battery, power, input (ui-spec §6, §8)
PAIR_SPLIT_S = 30
PAIR_GO_MS = 1000  # split: GO shown 1 s at 0
PAIR_READY_HINT_MS = 5000  # split: chip TAP WHEN READY from 5 s in
PAIR_READY_LEFT_S = 3  # split: both ready -> the countdown jumps to 3
CAL_GATE_WINDOW_MS = 1000  # RSSI sd over 1 s > unstable_sd pauses the fill
SEARCHING_WALK_ABOUT_MS = 45000
KNOCK_TOUCH_BEFORE_MS = 300  # a touch whose touch-down a counted spike precedes by up to this
KNOCK_TOUCH_AFTER_MS = 100  # ... or follows by up to this may be a knock's (§8) ...
# ... so it waits this long after the spike for the partner's: a knock spikes both watches, a finger only its own
KNOCK_WAIT_MS = 500
BUMP_ODR_HZ = 800  # accelerometer rate while a bump can count
BUMP_REFRACTORY_MS = 200
BUMP_READY_HOLD_MS = 1500  # band <3 held 1.5 s
BUMP_READY_BAND = 0  # index of '<3'
HOT_SCAN_PRESS_MS = 1000  # HOT: 2nd short press within this starts a scan (§8)
FOUND_CELEBRATE_MS = 2000
PARTNER_LEFT_MS = 2000  # partner in PAIRING this long: it left (§6 MENU)
BATT_SHUTDOWN_PCT = 3
BATT_INTERSTITIAL_MS = 2500
BATT_SCREEN_OFF_MS = 3000  # 5 %: screen off 3 s after lowering (LOW-BATTERY)
BYE_WORD_MS = 2000
GOODBYE_BEACONS = 3
GOODBYE_GRACE_MS = 1000  # power off this long after the BYE word (§6 LOW-BATTERY)
LOST_TIMER_MAX_S = 599  # m:ss up to 9:59, then 10M+
LOST_HINT_AFTER_MS = 20000  # GO BACK / KEEP ON
WAKE_BOOST_MS = 3000
WRIST_DOWN_MS = 10000  # on battery: screen off once lowered this long (§8)
WRIST_DOWN_DEG = 60  # lowered: tilted more than this from face-up
SCAN_READY_DOWN_MS = 2000  # scan ready: cancels once not flat this long
IDLE_DIM_MS = 30000
IDLE_DIM_BACKLIGHT = 0.35  # ui-spec §8: face-up > 30 s with no input
STATUS_AFTER_WAKE_MS = 3000
HINT_CHIP_MS = 4000  # TAP TO SCAN / LOOK AROUND
HINT_STILL_MS = 6000  # TAP TO SCAN after 6 s still with no arrow
TAP_MIN_MS = 60
TAP_MAX_MS = 400
TAP_MOVE_PX = 12
TAP_R_MAX_PX = 92
LONG_PRESS_MS = 800
WAKE_TOUCH_IGNORE_MS = 300
TOUCH_BURST_COUNT = 3  # >= 3 touches in 1 s ...
TOUCH_BURST_WINDOW_MS = 1000
TOUCH_BURST_IGNORE_MS = 2000  # ... ignore touches for 2 s
MENU_AUTOCLOSE_MS = 8000
MENU_CONFIRM_MS = 3000
MENU_ROWS_Y = (32, 76, 120, 164)
MENU_ROW_H = 40
