"""Golden ripple-field palettes for the C++ port (runs under MicroPython).

    node tools/mpy/run.mjs native/tools/golden_field.py > native/test/golden_field.txt

Drives the real ui/renderer.py (its field part: ``_step`` then ``_palette``)
through SEQS, the tools/bench_frame.py fixtures alone and chained, on an
uneven frame clock (DTS), and prints one FNV-1a hash of palette entries
0..169 per frame. native/test/test_field.cpp replays the same sequences
through sf::FieldScene and must reach the same hashes. The renderer needs
framebuf, so this runs on MicroPython only (tests/test_native.py checks the
committed file there).
"""

from finder.render_params import make_params
from ui.field import N_IDX, W, build_map
from ui.renderer import Renderer

# tools/bench_frame.py FIXTURES (it imports machine, so they are repeated here)
_FIELD = dict(ramp="green", ring_live=True, glyph="glow", status=(80, 80, 4, False, False))
FIXTURES = (
    dict(screen="FAR", zone=0, intensity=0.12, speed_px_s=40, pulse_period_ms=2400,
         wavelength_px=96, glow_r_px=25, dist_band="~20"),
    dict(screen="HOT", zone=3, intensity=0.85, speed_px_s=120, pulse_period_ms=500,
         wavelength_px=60, glow_r_px=54, dist_band="<3", word="BUMP!", top_text="TAP WATCHES"),
    dict(screen="PAIRING", sub="seen", zone=None, intensity=0.1, speed_px_s=-30,
         pulse_period_ms=3000, wavelength_px=90, glow_r_px=30, glyph="runes", runes=(0, 3, 6)),
)
# (fixture, frames) segments per sequence
SEQS = (
    ((0, 200),),
    ((1, 200),),
    ((2, 200),),
    ((0, 60), (1, 60), (2, 60), (0, 60)),
)
DTS = (33, 33, 34, 50, 17, 100, 33, 250, 1, 33)   # frame intervals, ms (cycled)
T0 = 10000


def fnv1a(words, n):
    """FNV-1a over the first n 16-bit words, little-endian bytes."""
    h = 0x811C9DC5
    for i in range(n):
        w = words[i]
        for b in (w & 0xFF, w >> 8):
            h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    return h


def lines():
    """The golden file, line by line."""
    yield "# GENERATED by native/tools/golden_field.py (MicroPython) -- DO NOT EDIT"
    yield "# map <fnv1a of the 240x240 ring-index map>"
    yield "# <seq> <frame> <t_ms> <fnv1a of palette entries 0..169>"
    m = build_map(W)
    h = 0x811C9DC5
    for b in m:
        h = ((h ^ b) * 0x01000193) & 0xFFFFFFFF
    yield "map %08x" % h
    for s, seq in enumerate(SEQS):
        r = Renderer()
        t = T0
        k = 0
        for fx, n in seq:
            kw = dict(_FIELD)
            kw.update(FIXTURES[fx])
            p = make_params(**kw)
            for _ in range(n):
                r._step(p, t)
                r._palette(p, t)
                yield "%d %d %d %08x" % (s, k, t, fnv1a(r.field.pal_arr, N_IDX))
                t += DTS[k % len(DTS)]
                k += 1


if __name__ == "__main__":
    for line in lines():
        print(line)
