"""Renderer tables and snapshot fixtures for the C++ renderer port (CPython).

    python3 native/tools/golden_frames.py            # (re)write both outputs
    python3 native/tools/golden_frames.py --check    # exit 1 if one is stale

native/core/include/hm/ui_tables.h: what ui/glyphs.py derives at import with
floats (mitred offsets, arc bands, rune strokes, bin culling rows), copied so
the C++ renderer draws the very polygons the MicroPython one does (CPython and
the wasm port compute the same tables); the glyph overrides of ui/font.py; and
the strings and times the renderer keys on that come from finder/ (the
calibrate pause chip, the scan's HOLD FLAT hint and blink phase, the FOUND
and BUMP! words).

native/test/golden/frames.txt: each tools/render_snapshots.py fixture as its
run time and phases (offset ms and every RenderParams field, in
native/tools/golden/render_params.py's token format). native/test/
test_renderer.cpp rebuilds each fixture's frames as render_snapshots.py's
render_fixture does (one Renderer, reset per fixture, a frame every FPS_MS
from T0, params with t_ms = T0 + t) and checks the last frame's CRC-32
against tests/snapshot_crc.json, which the MicroPython renderer wrote.
"""

import os
import sys
import types

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)

from finder import game, pairing, scan  # noqa: E402
from tools import render_snapshots as rs  # noqa: E402
from ui import glyphs as gl  # noqa: E402

HEADER = os.path.join(ROOT, "native", "core", "include", "hm", "ui_tables.h")
GOLDEN = os.path.join(ROOT, "native", "test", "golden", "frames.txt")


def _load(path, name):
    ns = {"__name__": name, "__file__": path}
    with open(path) as f:
        exec(f.read(), ns)
    return ns


def _font():
    """ui/font.py, which imports framebuf only to call framebuf.text."""
    had = "framebuf" in sys.modules
    if not had:
        sys.modules["framebuf"] = types.ModuleType("framebuf")
    try:
        from ui import font
    finally:
        if not had:
            del sys.modules["framebuf"]
    return font


def _cstr(s):
    assert all(" " <= c <= "~" and c not in '"\\' for c in s), s
    return '"%s"' % s


def _arr(ty, name, vals):
    return "constexpr %s %s[%d] = {%s};" % (ty, name, len(vals), ", ".join(str(v) for v in vals))


def header():
    out = [
        "// Renderer tables: ui/glyphs.py's import-time geometry, ui/font.py's glyph",
        "// overrides and the finder/ strings and times the renderer keys on.",
        "// GENERATED by native/tools/golden_frames.py -- DO NOT EDIT.",
        "// Regenerate: python3 native/tools/golden_frames.py   (check: --check)",
        "#pragma once",
        "#include <stdint.h>",
        "",
        "namespace hm {",
        "namespace ui {",
        "namespace U {",
        "",
        "// polygons: x, y per vertex (the dart in Q4 px, the rest in px)",
    ]
    for n in ("DART_Q4", "DART_KEY_Q4", "DART_IN_Q4", "CHEV_UP", "CHEV_DN_OUT", "CHEV_DN_IN", "CHECK_A",
              "TURN_R", "TURN_R_HEAD", "MARK_UP", "MARK_DN_OUT", "MARK_DN_IN", "DIAMOND"):
        v = getattr(gl, n)
        assert v.typecode == "h" and len(v) % 2 == 0, n
        out.append(_arr("int16_t", n, list(v)))
    out.append("// scan bin k's culling rows: y0 (first) and y1 (one past the last)")
    out.append(_arr("uint8_t", "BIN_Y0", list(gl.BIN_Y0)))
    out.append(_arr("uint8_t", "BIN_Y1", list(gl.BIN_Y1)))
    # runes: ops of rune k are RUNE_OPS[RUNE_FIRST[k]] .. RUNE_OPS[RUNE_FIRST[k + 1] - 1]
    ops, quads, first = [], [], []
    for rune in gl.RUNES:
        first.append(len(ops))
        for op in rune:
            if op[0] == gl.R_POLY:
                assert len(op[1]) == 8
                ops.append((op[0], len(quads), 0, 0))
                quads.append(list(op[1]))
            else:
                ops.append(tuple(op))
    first.append(len(ops))
    out += [
        "// rune ops: {kind, x, y, r}; a R_POLY op's x is its index in RUNE_QUADS",
        "constexpr int R_POLY = %d, R_DISC = %d, R_RING = %d, R_CUT = %d;" % (gl.R_POLY, gl.R_DISC, gl.R_RING,
                                                                            gl.R_CUT),
        _arr("uint8_t", "RUNE_FIRST", first),
        "constexpr int16_t RUNE_OPS[%d][4] = {%s};" % (len(ops), ", ".join(
            "{%s}" % ", ".join(str(v) for v in op) for op in ops)),
        "constexpr int16_t RUNE_QUADS[%d][8] = {%s};" % (len(quads), ", ".join(
            "{%s}" % ", ".join(str(v) for v in q) for q in quads)),
    ]
    font = _font()
    chars = sorted(font.OVERRIDE)
    assert all(len(c) == 1 and " " <= c <= "~" for c in chars)
    out += [
        "// ui/font.py OVERRIDE: 8 row bytes (MSB = left pixel) replacing a built-in glyph",
        "constexpr const char FONT_OVERRIDE[] = %s;" % _cstr("".join(chars)),
        "constexpr uint8_t FONT_OVERRIDE_ROWS[%d][8] = {%s};" % (len(chars), ", ".join(
            "{%s}" % ", ".join("0x%02X" % b for b in font.OVERRIDE[c]) for c in chars)),
        _arr("int32_t", "FACE_SX", list(font.SX)),
        _arr("int32_t", "FACE_SY", list(font.SY)),
        "// keys from finder/",
        "constexpr const char CAL_PAUSE[] = %s;     // pairing.HINT_HOLD_STILL" % _cstr(pairing.HINT_HOLD_STILL),
        "constexpr const char HINT_FLAT[] = %s;      // scan.HINT_FLAT" % _cstr(scan.HINT_FLAT),
        "constexpr int32_t SCAN_BLINK_PHASE_MS = %d;   // scan.BLINK_MS" % scan.BLINK_MS,
        "constexpr const char W_FOUND[] = %s;        // game.W_FOUND" % _cstr(game.W_FOUND),
        "constexpr const char W_BUMP[] = %s;         // game.W_BUMP" % _cstr(game.W_BUMP),
        "",
        "}  // namespace U",
        "}  // namespace ui",
        "}  // namespace hm",
        "",
    ]
    return "\n".join(out)


def golden():
    rp = _load(os.path.join(ROOT, "native", "tools", "golden", "render_params.py"), "golden_render_params")
    out = [
        "# GENERATED by native/tools/golden_frames.py from tools/render_snapshots.py -- DO NOT EDIT",
        "# t0 <T0> fps_ms <FPS_MS>",
        "# fixture <name> <run_ms> <phases>, then per phase:",
        "# phase <offset_ms> <make_params(t_ms=T0, **kw) as field tokens>",
        "t0 %d fps_ms %d" % (rs.T0, rs.FPS_MS),
    ]
    for name, phases, run_ms in rs.FIXTURES:
        out.append("fixture %s %d %d" % (name, run_ms, len(phases)))
        for off, kw in phases:
            p = rs.make_params(t_ms=rs.T0, **kw)
            assert rp["representable"](p), name
            out.append("phase %d %s" % (off, rp["toks"](p)))
    return "\n".join(out) + "\n"


OUTPUTS = ((HEADER, header), (GOLDEN, golden))


def stale():
    """Outputs (repo-relative) whose committed text differs from what the Python now produces."""
    bad = []
    for path, gen in OUTPUTS:
        try:
            with open(path) as f:
                have = f.read()
        except OSError:
            have = None
        if have != gen():
            bad.append(os.path.relpath(path, ROOT))
    return bad


def main(args):
    if args not in ([], ["--check"]):
        print(__doc__)
        return 2
    if args:
        bad = stale()
        for p in bad:
            print("%s is stale: run python3 native/tools/golden_frames.py" % p)
        return 1 if bad else 0
    for path, gen in OUTPUTS:
        with open(path, "w") as f:
            f.write(gen())
        print("wrote %s" % os.path.relpath(path, ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
