"""Golden vectors for the C++ port of the game logic (CPython).

    python3 native/tools/golden/run.py [name ...]           # (re)write native/test/golden/<name>.txt
    python3 native/tools/golden/run.py --check [name ...]   # exit 1 if one is stale

Each native/tools/golden/<name>.py drives the real finder/ module through
fixed inputs and yields text lines from ``lines()``; native/test/test_<name>.cpp
replays the same inputs through the C++ port and must match. When a finder/
module changes behaviour its file goes stale: regenerate, then port the change
until ``python3 native/test/run.py`` passes again. A module with a trace port
(native/test/test_port_*.cpp) has no golden file: its fixed inputs move to
native/tools/scenarios/ and are replayed as traces.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(os.path.dirname(HERE)))
OUT = os.path.join(ROOT, "native", "test", "golden")
sys.path.insert(0, ROOT)


def names():
    return sorted(f[:-3] for f in os.listdir(HERE) if f.endswith(".py") and f != "run.py")


def generate(name):
    ns = {"__name__": "golden_" + name, "__file__": os.path.join(HERE, name + ".py")}
    with open(ns["__file__"]) as f:
        exec(f.read(), ns)
    head = "# GENERATED by native/tools/golden/%s.py from the Python game -- DO NOT EDIT" % name
    return "\n".join([head] + list(ns["lines"]())) + "\n"


def stale(which=None):
    """Names whose committed file differs from what the Python now produces."""
    out = []
    for n in which or names():
        try:
            with open(os.path.join(OUT, n + ".txt")) as f:
                have = f.read()
        except OSError:
            have = None
        if have != generate(n):
            out.append(n)
    return out


def main(argv):
    check = "--check" in argv
    which = [a for a in argv if not a.startswith("--")] or names()
    if check:
        bad = stale(which)
        for n in bad:
            print("native/test/golden/%s.txt is stale" % n)
        return 1 if bad else 0
    os.makedirs(OUT, exist_ok=True)
    for n in which:
        with open(os.path.join(OUT, n + ".txt"), "w") as f:
            f.write(generate(n))
        print("wrote native/test/golden/%s.txt" % n)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
